import { Fragment as _Fragment, jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { memo } from "react";
// Browser preview is a readout, not a second browser.
// We only render backend-provided screenshots or controlled state
// representations. Never inject untrusted page HTML into the frontend.
// (DESIGN.md #14.2)
export const ScreenshotPreview = memo(function ScreenshotPreview({ state }) {
    const task = state.task;
    return (_jsxs("div", { className: "rounded-none border-1px line bg-surface-1 p-4", children: [_jsxs("div", { className: "mb-3 flex items-center justify-between", children: [_jsx("h3", { className: "text-muted text-[11px] uppercase tracking-wider-safe", children: "BROWSER PREVIEW" }), _jsx("span", { className: "text-muted text-[11px] data-mono", children: "READOUT ONLY" })] }), _jsx("div", { className: "aspect-video border-1px line-strong bg-surface-2 overflow-hidden", children: _jsx("div", { className: "flex h-full items-center justify-center text-muted text-[12px] data-mono", children: task ? (_jsxs(_Fragment, { children: [_jsxs("span", { className: "block leading-relaxed", children: ["ORIGIN: ", task.authority ?? "UNKNOWN"] }), _jsxs("span", { className: "block leading-relaxed", children: ["EPOCH: ", task.progress ?? "UNKNOWN"] })] })) : ("NO TASK ACTIVE") }) }), _jsxs("div", { className: "mt-3 flex flex-wrap gap-x-6 gap-y-1 text-[12px]", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-muted label-uppercase", children: "ORIGIN" }), _jsx("span", { className: "text-primary data-mono", children: task?.authority ?? "UNKNOWN" })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-muted label-uppercase", children: "EPOCH" }), _jsx("span", { className: "text-primary data-mono", children: task?.progress ?? "UNKNOWN" })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-muted label-uppercase", children: "LOADER" }), _jsx("span", { className: "text-muted data-mono", children: "\u2014" })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-muted label-uppercase", children: "FRAMES" }), _jsx("span", { className: "text-muted data-mono", children: "\u2014" })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-muted label-uppercase", children: "PROCESS CLASS" }), _jsx("span", { className: "text-muted data-mono", children: "\u2014" })] })] }), _jsx("p", { className: "mt-4 border-t-1px line pt-3 text-muted text-[11px] leading-relaxed", children: "The preview cannot become the authorization surface." })] }));
});
